# Generated by Django 4.2.5 on 2023-09-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True, help_text='Описание программы', null=True, verbose_name='Описание группы')),
                ('reg_start', models.DateTimeField(verbose_name='дата начала регистрации')),
                ('reg_end', models.DateTimeField(verbose_name='дата конца регистрации')),
                ('edu_start', models.DateTimeField(verbose_name='дата начала обучения')),
                ('edu_end', models.DateTimeField(verbose_name='дата конца обучения')),
                ('is_intramural', models.BooleanField(default=True, verbose_name='флаг очной формы')),
                ('is_free', models.BooleanField()),
                ('text', models.TextField(verbose_name='подробное описание программы')),
            ],
            options={
                'verbose_name': 'Учебная программа',
                'verbose_name_plural': 'Учебные программы',
            },
        ),
    ]
