# Generated by Django 4.2.5 on 2023-11-15 07:47

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('edu_progs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('created', models.DateField(verbose_name='Дата заявки')),
                ('handled', models.DateField(blank=True, null=True, verbose_name='Дата обработки')),
                ('is_handled', models.BooleanField(default=False, verbose_name='Заявка обработана')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Заметка для менеджера')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_progs.program', verbose_name='Программа в заявке')),
            ],
            options={
                'verbose_name': 'Заявка на программу',
                'verbose_name_plural': 'Заявки на программы',
            },
        ),
    ]
