# Generated by Django 4.2.5 on 2023-09-28 10:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('edu_progs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programm',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='programs/images'),
            preserve_default=False,
        ),
    ]
