# Generated by Django 4.2.5 on 2023-11-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_progs', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя заявителя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Дата заявки'),
        ),
    ]
