# Generated by Django 4.2.5 on 2023-09-28 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_progs', '0002_programm_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Programm',
            new_name='Program',
        ),
    ]
