# Generated by Django 4.2.5 on 2023-09-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_progs', '0003_rename_programm_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='hours',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Трудоёмкость'),
        ),
        migrations.AddField(
            model_name='program',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Программа опубликована'),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True, help_text='Описание программы', null=True, verbose_name='Описание программы'),
        ),
        migrations.AlterField(
            model_name='program',
            name='edu_end',
            field=models.DateField(verbose_name='Дата конца обучения'),
        ),
        migrations.AlterField(
            model_name='program',
            name='edu_start',
            field=models.DateField(verbose_name='Дата начала обучения'),
        ),
        migrations.AlterField(
            model_name='program',
            name='image',
            field=models.ImageField(upload_to='programs/images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='program',
            name='is_free',
            field=models.BooleanField(verbose_name='Бесплатная программа'),
        ),
        migrations.AlterField(
            model_name='program',
            name='is_intramural',
            field=models.BooleanField(default=True, verbose_name='Очная форма'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=140, verbose_name='Имя программы'),
        ),
        migrations.AlterField(
            model_name='program',
            name='reg_end',
            field=models.DateField(verbose_name='Дата конца регистрации'),
        ),
        migrations.AlterField(
            model_name='program',
            name='reg_start',
            field=models.DateField(verbose_name='Дата начала регистрации'),
        ),
        migrations.AlterField(
            model_name='program',
            name='text',
            field=models.TextField(verbose_name='Подробное описание программы'),
        ),
    ]
