# Generated by Django 4.2.5 on 2023-10-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(help_text='Заголовок поста', max_length=140, verbose_name='Заголовок поста')),
                ('description', models.CharField(blank=True, help_text='Метатег description', max_length=160, null=True, verbose_name='Метатег description')),
                ('title', models.CharField(blank=True, help_text='Метатег title', max_length=65, null=True, verbose_name='Метатег title')),
                ('short_story', models.TextField(help_text='Краткая новость', verbose_name='Краткая новость')),
                ('full_story', models.TextField(blank=True, help_text='Полная новость', null=True, verbose_name='Полная новость')),
                ('date', models.DateTimeField(help_text='Дата публикации', verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(verbose_name='Пост опубликован')),
            ],
            options={
                'verbose_name': 'Новостной пост',
                'verbose_name_plural': 'Новостные посты',
            },
        ),
    ]
