# Generated by Django 4.2.5 on 2023-10-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='full_story',
            field=models.TextField(blank=True, help_text='Полная новость', null=True, verbose_name='Полная новость'),
        ),
        migrations.AlterField(
            model_name='post',
            name='h1',
            field=models.CharField(help_text='Заголовок поста', max_length=140, verbose_name='Заголовок поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_story',
            field=models.TextField(help_text='Краткая новость', verbose_name='Краткая новость'),
        ),
    ]
