# Generated by Django 4.2.5 on 2023-11-22 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/images', verbose_name='Image')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='news.post', verbose_name='Пост, в котором будет изображение')),
            ],
            options={
                'verbose_name': 'Изображение в посте',
                'verbose_name_plural': 'Изображения в постах',
            },
        ),
    ]
