# Generated by Django 4.2.5 on 2024-06-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_delete_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0, help_text='Число охваченных людей', verbose_name='Число охваченных людей')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
